version: '2'
services:

  sonar:
    build:
      context: .
    restart: always
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-ext:/opt/sonarqube/extensions
    networks:
      - sonar
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgresql:5432/sonar"

  postgresql:
    image: postgres:9.5.3
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - sonar
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar

volumes:
  sonar-data:
    external: false
  sonar-ext:
    external: false
  postgresql:
    external: false

networks:
  sonar:
    driver: bridge
