version: '2'
services:

  nginx:
    image: nginx:1.11.0
    restart: always
    network_mode: "host"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/http.conf:/etc/nginx/conf.d/http.conf:ro
